#!/usr/bin/env bash

SCRIPT_NAME="${BASH_SOURCE[0]}"

if [ "${#}" != "2" ]; then
    echo "Usage: ${SCRIPT_NAME} infile outfile."
    exit 1
fi

INFILE="${*: -2:1}"
OUTFILE="${*: -1:1}"

exec "${SCRIPT_NAME}.bin" "${@:1:${#}-2}" "${INFILE}" "${OUTFILE}"
